"""Initial migration

Revision ID: 771555241255
Revises: 1ed43776064f
Create Date: 2017-04-24 09:15:59.549855

"""


# revision identifiers, used by Alembic.
revision = '771555241255'
down_revision = '1ed43776064f'
branch_labels = ('hotel',)
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('notes', sa.Unicode(), server_default='', nullable=False),
    sa.Column('message', sa.Unicode(), server_default='', nullable=False),
    sa.Column('locked_in', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('nights', sa.Unicode(), server_default='', nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room'))
    )
    op.create_table('hotel_requests',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('attendee_id', postgresql.UUID(), nullable=False),
    sa.Column('nights', sa.Unicode(), server_default='', nullable=False),
    sa.Column('wanted_roommates', sa.Unicode(), server_default='', nullable=False),
    sa.Column('unwanted_roommates', sa.Unicode(), server_default='', nullable=False),
    sa.Column('special_needs', sa.Unicode(), server_default='', nullable=False),
    sa.Column('approved', sa.Boolean(), server_default='False', nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendee.id'], name=op.f('fk_hotel_requests_attendee_id_attendee')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotel_requests')),
    sa.UniqueConstraint('attendee_id', name=op.f('uq_hotel_requests_attendee_id'))
    )
    op.create_table('room_assignment',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('room_id', postgresql.UUID(), nullable=False),
    sa.Column('attendee_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendee.id'], name=op.f('fk_room_assignment_attendee_id_attendee')),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('fk_room_assignment_room_id_room')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_assignment'))
    )
    op.add_column('attendee', sa.Column('hotel_eligible', sa.Boolean(), server_default='False', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendee', 'hotel_eligible')
    op.drop_table('room_assignment')
    op.drop_table('hotel_requests')
    op.drop_table('room')
    ### end Alembic commands ###
